# -*- coding: utf-8 -*-
"""yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rservw6afoxXDgHp1ZCkeo1GRbAG9TRv

# Plastic Detection using YOLOv8

This project focuses on detecting plastic waste using computer vision.

## Objectives
- Detect plastic objects
- Train YOLOv8 model
- Evaluate performance

## Analysis

The model performs well overall but struggles with:
- Cloth (low data)
- Container (few samples)

Main limitation:
- Small dataset (254 images)

## Improvements

- Increase dataset size
- Balance classes
- Use YOLOv8s instead of YOLOv8n
"""

!pip install ultralytics
!pip install roboflow

import os
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
from roboflow import Roboflow

rf = Roboflow(api_key="NONi9nEaxC3EYilr7NvC")
project = rf.workspace("yolo-lnkrj").project("plastic-detection-pywxk")
version = project.version(4)
dataset = version.download("yolov8")

base_path = dataset.location
images_path = f"{base_path}/train/images"

images = os.listdir(images_path)

print(f"Number of training images: {len(images)}")

plt.figure(figsize=(10,5))

for i, img_name in enumerate(images[:5]):

    img = cv2.imread(os.path.join(images_path, img_name))

    if img is None:
        continue

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(1,5,i+1)
    plt.imshow(img)
    plt.title(f"Image {i+1}")
    plt.axis("off")

plt.tight_layout()
plt.show()

model = YOLO("yolov8n.pt")
model.train(data=f"{dataset.location}/data.yaml", epochs=50,augment=True)

model = YOLO("/content/runs/detect/train/weights/best.pt")
metrics=model.val()

print("\n=== Résultats du modèle ===")
print(f"Precision (P): {metrics.box.p.mean():.3f}")
print(f"Recall (R): {metrics.box.r.mean():.3f}")
print(f"mAP50: {metrics.box.map50:.3f}")
print(f"mAP50-95: {metrics.box.map:.3f}")

#results = model.predict(source="/content/Capture d’écran 2026-04-03 175150.jpg", show=True,save=True)

images_path = os.path.join(base_path, "test/images")
labels_path = os.path.join(base_path, "test/labels")

images = os.listdir(images_path)

plt.figure(figsize=(12,5))

for i, img_name in enumerate(images[:5]):

    img_path = os.path.join(images_path, img_name)
    img = cv2.imread(img_path)

    if img is None:
        continue

    h, w, _ = img.shape

    label_name = img_name.replace(".jpg", ".txt").replace(".png", ".txt")
    label_path = os.path.join(labels_path, label_name)

    if os.path.exists(label_path):
        with open(label_path, "r") as f:
            for line in f.readlines():
                cls, x, y, bw, bh = map(float, line.split())

                x1 = int((x - bw/2) * w)
                y1 = int((y - bh/2) * h)
                x2 = int((x + bw/2) * w)
                y2 = int((y + bh/2) * h)

                cv2.rectangle(img, (x1, y1), (x2, y2), (0,255,0), 2)
                cv2.putText(img, f"class {int(cls)}", (x1, y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(1,5,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.tight_layout()
plt.show()